name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install virtualenv wheel
          virtualenv venv
          ./venv/Scripts/activate
          python -m pip install -r windows/requirements.txt
          python -m pip install pyinstaller
          python -m pip install .
      - name: Build
        run: |
          ./venv/Scripts/activate
          pyinstaller.exe windows/pywebdriver.spec
      - name: Test build
        shell: bash
        run: |
          timeout 3s ./dist/pywebdriver/pywebdriver.exe || test "$?" = 124
      - name: prepare release
        run: |
          7z a pywebdriver_$(date +%Y%m%d)_win64.zip dist/pywebdriver
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pywebdriver_$(date +%Y%m%d)_win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          sudo apt-get install libnss3-tools libcups2-dev cups devscripts debhelper dh-virtualenv dh-systemd python3-wheel python3-setuptools python3-venv libmtp-dev libffi-dev fakeroot
          python -m pip install -r requirements.txt
      - name: Build
        run: |
          mkdir -p build
          dch --package pywebdriver --newversion $(date +%Y%m%d) --create -m "Created by travis"
          debuild
      - name: Test build
        run: |
          sudo dpkg -i ../pywebdriver_$(date +%Y%m%d)_amd64.deb
          sh debian/replace_snakeoil_mkcert.sh
          sudo journalctl -u pywebdriver
          sudo service pywebdriver status
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ../pywebdriver_$(date +%Y%m%d)_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
